version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - .dockervenv:/src/.venv
      - ./backend:/src
      - ./.env:/src/.env
    ports:
      - 8000:8000
  db:
    image: postgres:16
    volumes:
      - fastapi_postgres_data:/db
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    ports:
      - 15432:5432
  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  # TODO: frontendのコンテナも用意する

volumes:
  fastapi_postgres_data:
