"""add price columns to cars table

Revision ID: e744b09ad211
Revises: 5b16d0495409
Create Date: 2024-10-16 07:41:18.943491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e744b09ad211"
down_revision: Union[str, None] = "5b16d0495409"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cars",
        sa.Column(
            "price_for_initial_twelve_hours",
            sa.Integer(),
            server_default="13000",
            nullable=False,
        ),
    )
    op.add_column(
        "cars",
        sa.Column(
            "price_per_additional_six_hours",
            sa.Integer(),
            server_default="6000",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "price_per_additional_six_hours")
    op.drop_column("cars", "price_for_initial_twelve_hours")
    # ### end Alembic commands ###
